### ISSUE TITLE
Reuse the default markup renderer when overriding a markup renderer

### ISSUE THREAD

**Issue by YoranBrondsema** [bustle/mobiledoc-dom-renderer#56]
It would be good to be able to reuse the default markup or section renderer when overriding one. For instance, in the example for the [markup renderer for `<a>`](https://github.com/bustle/mobiledoc-dom-renderer#markupelementrenderer), the resulting renderer is vulnerable for XSS as the URL sanitization only happens in the default renderer.

Instead, it would be better to be able to write the example as something like:

```javascript
import { A } from 'mobiledoc-dom-renderer/markup-element-renderer';

let renderer = new MobiledocDOMRenderer({
  markupElementRenderer: {
    A(tagName, dom, attrs={}) {
      let element = A(...arguments);
      element.setAttribute('rel', 'nofollow');
      return element;
    }
  }
});
```

This way, the client app can still make use of whatever security mechanisms are implemented in the default renderer. In my case, I had to copy the code for URL sanitization into my renderer for <a>.

I think this can be achieved relatively easily by exporting the default section and markup renderers and allowing a client app to consume them.

**Comment by gpoitch** [comment]
Should be able to do this already:
```js
const { defaultMarkupElementRenderer } = require('mobiledoc-dom-renderer/lib/utils/render-utils')

const customRenderer = new MobiledocDOMRenderer({
  markupElementRenderer: {
    A(tagName, dom, attrs) {
      const element = defaultMarkupElementRenderer(...arguments)
      // customize...
      return element
    }
  }
})
```
Would accept a PR for an official export.
